export { default as DefaultLayout } from './defaultLayout/defaultLayout';
export { default as Navbar } from './navbar/navbar';
export { default as Sidebar } from './sidebar/sidebar';
export { default as PostMain } from './main/video/post';
export { default as PostMainLike } from './main/postMainLike/postMainLike';
export { default as WarningPopup } from './popup/popup'
export { default as TextInput } from './textInput/textInput'
export { default as PostUser } from './main/video/postUser'
export { default as EditProfileOverlay } from './editProfile/editProfile'
export { default as CommentHeader } from './comment/commentHeader'
export { default as CommentBody } from './comment/commentBody'
export { default as Login } from './auth/login'
export { default as Register } from './auth/register'
export { default as AuthOverlay } from './auth/AuthOverlay'